# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170629_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(related_name='friends', to='login.User'),
        ),
    ]
